### ISSUE TITLE
Additional Employee Interface

### ISSUE THREAD

**Issue by Arifah0100** [Arifah0100/ABS-Information-System#4]
Create new interface for employee 'Manager', a one-to-one relation to Manager Entity.

Manager - the one who manage the collectors or employee.
Attribute:
  manageID: number;
  firstName: string;
  middleName: string;
  lastName: string;
  startDate: string;
  department: string;
  position: string;

**Comment by Arifah0100** [comment]
kelangan ng additional attribute ng employee na 'manager' which is in one-to-one relation with MAnagerDto

**Comment by basamserad** [comment]
Is manager employee id?

**Comment by Arifah0100** [comment]
hnd po. foreign key po from the Manager DTO..

**Comment by Arifah0100** [comment]
Pardon. This issue should be in the serverside. once again. sorry 😌

**Comment by basamserad** [comment]
haha fighting
